const Map<String, String> _flags = {
  'bahrain': '🇧🇭',
  'saudi arabia': '🇸🇦',
  'australia': '🇦🇺',
  'japan': '🇯🇵',
  'china': '🇨🇳',
  'usa': '🇺🇸',
  'united states': '🇺🇸',
  'italy': '🇮🇹',
  'monaco': '🇲🇨',
  'canada': '🇨🇦',
  'spain': '🇪🇸',
  'austria': '🇦🇹',
  'uk': '🇬🇧',
  'united kingdom': '🇬🇧',
  'great britain': '🇬🇧',
  'hungary': '🇭🇺',
  'belgium': '🇧🇪',
  'netherlands': '🇳🇱',
  'singapore': '🇸🇬',
  'mexico': '🇲🇽',
  'brazil': '🇧🇷',
  'qatar': '🇶🇦',
  'uae': '🇦🇪',
  'united arab emirates': '🇦🇪',
  'azerbaijan': '🇦🇿',
  'france': '🇫🇷',
  'germany': '🇩🇪',
  'portugal': '🇵🇹',
  'turkey': '🇹🇷',
  'russia': '🇷🇺',
  'south korea': '🇰🇷',
};

String? flagFor(String country) => _flags[country.toLowerCase()];
